# Generated by Django 4.1.7 on 2023-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recette',
            name='personnes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_preparation',
            field=models.IntegerField(),
        ),
    ]
