# Generated by Django 4.2 on 2023-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
